import { Product } from '@/types';
import { getProductImages } from './utils';

export const FALLBACK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'LUX-01 Red Light Face Mask',
    slug: 'lux-01-red-light-face-mask',
    description: 'Clinical-grade red light therapy at home. Our LUX-01 mask uses 630nm + 850nm wavelengths to boost collagen production, reduce fine lines, and restore your natural glow in just 10 minutes a day. Non-invasive, FDA-cleared, and dermatologist-approved.',
    price: 89.99,
    compare_price: 149.99,
    images: getProductImages('lux-01-red-light-face-mask'),
    category: 'Light Therapy',
    stock: 80,
    rating: 4.9,
    review_count: 4728,
    is_featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'FROST-01 Facial Ice Bath Bowl',
    slug: 'frost-01-facial-ice-bath-bowl',
    description: 'Spa-quality cryotherapy at home. Reduce puffiness, tighten pores, and energize your skin with our BPA-free facial ice bath. The viral self-care ritual loved by millions — perfect for morning routines or post-workout recovery.',
    price: 34.99,
    compare_price: 54.99,
    images: getProductImages('frost-01-facial-ice-bath-bowl'),
    category: 'Recovery',
    stock: 120,
    rating: 4.7,
    review_count: 1203,
    is_featured: false,
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: '3',
    name: 'PULSE-01 Mini Massage Gun',
    slug: 'pulse-01-mini-massage-gun',
    description: 'Professional percussive therapy in your pocket. 6 speed settings and a whisper-quiet motor target muscle tension, speed recovery, and melt away stress. Compact enough for your bag, powerful enough for deep relief.',
    price: 54.99,
    compare_price: 89.99,
    images: getProductImages('pulse-01-mini-massage-gun'),
    category: 'Recovery',
    stock: 95,
    rating: 4.8,
    review_count: 2891,
    is_featured: false,
    created_at: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: '4',
    name: 'DREAM-01 Weighted Sleep Mask',
    slug: 'dream-01-weighted-sleep-mask',
    description: 'Drift into deeper sleep. Our weighted sleep mask applies gentle, calming pressure to relax your mind, block out light completely, and help you fall asleep faster. The perfect end to your recovery ritual.',
    price: 29.99,
    compare_price: 44.99,
    images: getProductImages('dream-01-weighted-sleep-mask'),
    category: 'Sleep & Relax',
    stock: 140,
    rating: 4.6,
    review_count: 856,
    is_featured: false,
    created_at: new Date(Date.now() - 259200000).toISOString(),
  },
];

export const FALLBACK_REVIEWS = [
  { id: '1', product_id: '1', author_name: 'Sarah M.', rating: 5, body: 'My skin has never looked better! After three weeks with the LUX-01 my fine lines have visibly softened and I get compliments constantly. The glow is real.', created_at: new Date().toISOString() },
  { id: '2', product_id: '1', author_name: 'Jessica L.', rating: 5, body: 'Worth every penny. I cancelled my facialist appointments — 10 minutes a day and my complexion is brighter than ever.', created_at: new Date().toISOString() },
  { id: '3', product_id: '1', author_name: 'Amara K.', rating: 5, body: 'Beautiful packaging, feels genuinely premium, and the results speak for themselves. This is the real deal.', created_at: new Date().toISOString() },
  { id: '4', product_id: '1', author_name: 'Maya T.', rating: 4, body: 'Took a couple weeks to notice but now I am hooked. The rose glow is part of my nightly ritual.', created_at: new Date().toISOString() },
  { id: '5', product_id: '1', author_name: 'Olivia R.', rating: 5, body: 'Dermatologist recommended and I can see why. Gentle, easy, and effective. Highly recommend.', created_at: new Date().toISOString() },
];
