import { Product } from '@/types';
import { getProductImages } from './utils';

export const FALLBACK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'ProRelax Sauna Blanket',
    slug: 'prorelax-sauna-blanket',
    description: 'Experience spa-level heat therapy at home. Our infrared sauna blanket promotes deep muscle relaxation, detoxification, and stress relief in just 30 minutes.',
    price: 79.99,
    compare_price: 119.99,
    images: getProductImages('prorelax-sauna-blanket'),
    category: 'Heat Therapy',
    stock: 50,
    rating: 4.8,
    review_count: 247,
    is_featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'NeckEase Massage Gun Pro',
    slug: 'neckease-massage-gun-pro',
    description: '6 adjustable speed settings, whisper-quiet motor. Targets neck, shoulders, and back tension with precision percussive therapy.',
    price: 54.99,
    compare_price: 89.99,
    images: getProductImages('neckease-massage-gun-pro'),
    category: 'Massage',
    stock: 75,
    rating: 4.7,
    review_count: 183,
    is_featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'GlowRevive Red Light Face Wand',
    slug: 'glowrevive-red-light-face-wand',
    description: 'Clinical-grade 630nm + 850nm wavelengths. Reduces fine lines, boosts collagen production, and accelerates skin recovery in 10 minutes daily.',
    price: 44.99,
    compare_price: 69.99,
    images: getProductImages('glowrevive-red-light-face-wand'),
    category: 'Skincare',
    stock: 100,
    rating: 4.9,
    review_count: 312,
    is_featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'DeepKnead Shiatsu Neck Massager',
    slug: 'deepknead-shiatsu-neck-massager',
    description: '3D rotating massage nodes with heat function. Mimics professional shiatsu massage for instant tension relief at home or in the car.',
    price: 39.99,
    compare_price: 59.99,
    images: getProductImages('deepknead-shiatsu-neck-massager'),
    category: 'Massage',
    stock: 60,
    rating: 4.6,
    review_count: 156,
    is_featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'IcePulse Facial Roller Set',
    slug: 'icepulse-facial-roller-set',
    description: 'Dual-ended rose quartz roller + gua sha stone. Reduces puffiness, boosts circulation, and enhances product absorption in your morning routine.',
    price: 24.99,
    compare_price: 39.99,
    images: getProductImages('icepulse-facial-roller-set'),
    category: 'Skincare',
    stock: 120,
    rating: 4.5,
    review_count: 428,
    is_featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'FlexWave EMS Muscle Stimulator',
    slug: 'flexwave-ems-muscle-stimulator',
    description: '16 intensity levels, 6 massage modes. FDA-cleared EMS technology for muscle recovery, pain relief, and passive workout enhancement.',
    price: 49.99,
    compare_price: 79.99,
    images: getProductImages('flexwave-ems-muscle-stimulator'),
    category: 'Recovery',
    stock: 45,
    rating: 4.7,
    review_count: 94,
    is_featured: false,
    created_at: new Date().toISOString(),
  },
];

export const FALLBACK_REVIEWS = [
  { id: '1', product_id: '1', author_name: 'Sarah M.', rating: 5, body: 'Absolutely love this! My back feels amazing after just one session. Shipping was fast and packaging was beautiful.', created_at: new Date().toISOString() },
  { id: '2', product_id: '1', author_name: 'James T.', rating: 5, body: 'Best purchase I made this year. Works perfectly and I use it every day.', created_at: new Date().toISOString() },
  { id: '3', product_id: '1', author_name: 'Emily R.', rating: 4, body: 'Great quality for the price. Noticed results within a week of consistent use.', created_at: new Date().toISOString() },
  { id: '4', product_id: '1', author_name: 'Michael K.', rating: 5, body: 'Worth every penny. My whole family now fights over it!', created_at: new Date().toISOString() },
  { id: '5', product_id: '1', author_name: 'Lisa P.', rating: 4, body: 'Super easy to use and feels very professional quality. Highly recommend.', created_at: new Date().toISOString() },
];
